### ISSUE TITLE
what version of discord.js is this?

### ISSUE THREAD

**Issue by Ravenwulf** [Spimy/muse#1]
Also, you dont mention anywhere in the readme that you need to npm install ytdl and yt-search and all the other things

**Comment by ItsAuric** [comment]
V12 Discord.js and also it's common sense to download the npms unless you just wanna fork without any knowledge or experience of a Discord bot.

**Comment by Spimy** [comment]
@Ravenwulf running `npm install` installs every packages needed for the bot since `package.json` contains all the needed information. It'll also install the correct version of said package. Simply rum `npm install` as stated in the README file.
