### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sonqs** [Spimy/muse#10]
internal/validators.js:112
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
←[90m    at validateString (internal/validators.js:112:11)←[39m
←[90m    at Url.parse (url.js:155:3)←[39m
←[90m    at Object.urlParse [as parse] (url.js:150:13)←[39m
    at doDownload (C:\Users\Zarko\Desktop\Waves\node_modules\←[4mminiget←[24m\dist\index.js:90:28)
←[90m    at processTicksAndRejections (internal/process/task_queues.js:76:11)←[39m {
  code: ←[32m'ERR_INVALID_ARG_TYPE'←[39m
}

**Comment by Spimy** [comment]
![image](https://user-images.githubusercontent.com/34989646/83280249-6c04e980-a1e7-11ea-8a07-5906bacba729.png)
