### ISSUE TITLE
stop error

### ISSUE THREAD

**Issue by snowdqdzq** [Spimy/muse#2]
There is a problem with the stop command if there is music in the queue it leaves the channel and rejoins it and plays the other music.

**Comment by Spimy** [comment]
That is not a bug. The stop command is made to clear the whole queue and leave the channel. This is in the code:
![image](https://user-images.githubusercontent.com/34989646/80022895-c4144600-84ed-11ea-9f1e-e3e98e47bf3f.png)

**Comment by snowdqdzq** [comment]
well if you put a playlist it does not stop

**Comment by Spimy** [comment]
Ah, okay. That happens when the playlist was still processing. You should've just said so from the beginning. I'll work on a fix asap.

**Comment by snowdqdzq** [comment]
sorry my english is bad i use google translate

**Comment by snowdqdzq** [comment]
sorry my english is bad i use google translate
