### ISSUE TITLE
Song queue affected by commands when not in VC

### ISSUE THREAD

**Issue by snowdqdzq** [Spimy/muse#3]
Error:
We can skip, change the volume, stop the music ... when we are not in the same channel as the bot.

**Comment by Spimy** [comment]
Open error and suggestion on separate issues. Edit this to error and recreate another for suggestion. It's for organisation purposes.

>Error:
We can skip, change the volume, stop the music ... when we are not in the same channel as the bot.

Will fix this asap. Forgot to handle that.

**Comment by Spimy** [comment]
Pushed the update to fix the bug. Release not out yet so feel free to clone the repo instead.
