### ISSUE TITLE
Skip vote be number of people in VC

### ISSUE THREAD

**Issue by snowdqdzq** [Spimy/muse#4]
I don't know how to explain too much but here are examples.

Example:

4 people in the voice channel = 2 votes for skip

7 people in the voice channel = 4 or 3 for skip.

10 people in the voice channel = 5 for skip...

Because if someone is alone in the channel they cannot skip as they need 3 votes.

**Comment by Spimy** [comment]
Will consider this. I'll make an optional choice, changeable in the config.

**Comment by Spimy** [comment]
Pushed the update to add this. However, the count is not divided by 2 as suggested. If you insist on this, please reopen the issue.
Release not out yet so feel free to clone the repo instead.
