### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Hadi-koubeissi** [Spimy/muse#7]
Hi there is a problem with the bot when I am in one room and the bot in another room and ask to play the song the bot plays the song in the other room Please fix the bug and make it when I request to play the song and the bot in another room is sending a message to me that the bot is not in my room

**Comment by ItsAuric** [comment]
You should be able to fix that by yourself, Muse is for users that want to apply features or want to just use it for personal use.

**Comment by Hadi-koubeissi** [comment]
I did it and fixed it, but I tell him to fix it here for people who don't know programming

**Comment by ItsAuric** [comment]
> I did it and fixed it, but I tell him to fix it here for people who don't know programming

The people who don't know programming must have an understanding of discord.js
